/** Stable API error codes for Spliton clients. */

export const ErrorCodes = {

  AUTH_REQUIRED: 'AUTH_REQUIRED',

  AUTH_INVALID: 'AUTH_INVALID',

  AUTH_2FA_REQUIRED: 'AUTH_2FA_REQUIRED',

  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',

  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',



  WALLET_INSUFFICIENT_BALANCE: 'WALLET_INSUFFICIENT_BALANCE',

  WALLET_FROZEN: 'WALLET_FROZEN',

  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',

  LEDGER_DRIFT_DETECTED: 'LEDGER_DRIFT_DETECTED',

  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',



  DEPOSIT_DUPLICATE_TX: 'DEPOSIT_DUPLICATE_TX',

  DEPOSIT_PROVIDER_UNAVAILABLE: 'DEPOSIT_PROVIDER_UNAVAILABLE',

  DEPOSIT_PENDING_CONFIRMATIONS: 'DEPOSIT_PENDING_CONFIRMATIONS',

  DEPOSIT_DISABLED: 'DEPOSIT_DISABLED',



  WITHDRAWAL_DISABLED: 'WITHDRAWAL_DISABLED',

  WITHDRAWAL_INVALID_STATE: 'WITHDRAWAL_INVALID_STATE',

  WITHDRAWAL_LIMIT_EXCEEDED: 'WITHDRAWAL_LIMIT_EXCEEDED',

  WITHDRAWAL_KYC_REQUIRED: 'WITHDRAWAL_KYC_REQUIRED',

  WITHDRAWAL_COMPLIANCE_HOLD: 'WITHDRAWAL_COMPLIANCE_HOLD',



  LISTING_NOT_FOUND: 'LISTING_NOT_FOUND',

  LISTING_NOT_ACTIVE: 'LISTING_NOT_ACTIVE',

  LISTING_OWN_BUY_FORBIDDEN: 'LISTING_OWN_BUY_FORBIDDEN',

  LISTING_FROZEN: 'LISTING_FROZEN',

  MARKET_DISABLED: 'MARKET_DISABLED',

  MARKET_DOUBLE_BUY_BLOCKED: 'MARKET_DOUBLE_BUY_BLOCKED',

  MARKET_INSUFFICIENT_UNITS: 'MARKET_INSUFFICIENT_UNITS',

  MARKET_COMPLIANCE_RESTRICTED: 'MARKET_COMPLIANCE_RESTRICTED',



  RELEASE_NOT_FOUND: 'RELEASE_NOT_FOUND',

  RELEASE_NOT_PUBLIC: 'RELEASE_NOT_PUBLIC',

  ROUND_SOLD_OUT: 'ROUND_SOLD_OUT',

  ROUND_PAUSED: 'ROUND_PAUSED',

  PURCHASE_DISABLED: 'PURCHASE_DISABLED',



  DOCUMENT_NOT_READY: 'DOCUMENT_NOT_READY',

  DOCUMENT_EXPIRED: 'DOCUMENT_EXPIRED',

  DOCUMENT_FORBIDDEN: 'DOCUMENT_FORBIDDEN',

  REPORT_FAILED: 'REPORT_FAILED',

  REPORT_NOT_READY: 'REPORT_NOT_READY',

  REPORT_FORBIDDEN: 'REPORT_FORBIDDEN',



  COMPLIANCE_RESTRICTED: 'COMPLIANCE_RESTRICTED',

  RISK_HOLD_ACTIVE: 'RISK_HOLD_ACTIVE',



  SYSTEM_MAINTENANCE: 'SYSTEM_MAINTENANCE',

  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',

  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',

  RATE_LIMITED: 'RATE_LIMITED',

  VALIDATION_ERROR: 'VALIDATION_ERROR',

  FEATURE_DISABLED: 'FEATURE_DISABLED',

  INTERNAL_ERROR: 'INTERNAL_ERROR',



  ADMIN_FORBIDDEN: 'ADMIN_FORBIDDEN',

} as const;



export type AppErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

