/**
 * Admin API paths — versioned operator surface.
 * Public user API: `/api/v1/...` (future) — never mix with admin financial mutations.
 */

import {
  getAdminApiBaseUrl,
  getAdminDataSource as getAdminDataSourceFromEnv,
  type DataSourceMode,
} from "@/lib/public-env";

export const ADMIN_API_V1_PREFIX = "/api/admin/v1";

/** Legacy gate — keep until all clients use v1 */
export const ADMIN_ACCESS_LEGACY = "/admin/access";

export const ADMIN_API_PATHS = {
  access: `${ADMIN_API_V1_PREFIX}/access`,
  search: `${ADMIN_API_V1_PREFIX}/search`,
  dashboardSummary: `${ADMIN_API_V1_PREFIX}/dashboard/summary`,
  dashboardTasks: `${ADMIN_API_V1_PREFIX}/dashboard/tasks`,
  dashboardRiskAlerts: `${ADMIN_API_V1_PREFIX}/dashboard/risk-alerts`,
  dashboardRecentActions: `${ADMIN_API_V1_PREFIX}/dashboard/recent-actions`,
  dashboardRecentDeposits: `${ADMIN_API_V1_PREFIX}/dashboard/recent-deposits`,
  dashboardRecentWithdrawals: `${ADMIN_API_V1_PREFIX}/dashboard/recent-withdrawals`,
  dashboardTrends: `${ADMIN_API_V1_PREFIX}/dashboard/trends`,
  dashboard: `${ADMIN_API_V1_PREFIX}/dashboard`,
  users: `${ADMIN_API_V1_PREFIX}/users`,
  usersStatsSummary: `${ADMIN_API_V1_PREFIX}/users/stats/summary`,
  user: (id: string) => `${ADMIN_API_V1_PREFIX}/users/${id}`,
  tracks: `${ADMIN_API_V1_PREFIX}/tracks`,
  track: (id: string) => `${ADMIN_API_V1_PREFIX}/tracks/${id}`,
  artists: `${ADMIN_API_V1_PREFIX}/artists`,
  artist: (id: string) => `${ADMIN_API_V1_PREFIX}/artists/${id}`,
  releaseGenres: `${ADMIN_API_V1_PREFIX}/release-genres`,
  releaseGenre: (id: string) => `${ADMIN_API_V1_PREFIX}/release-genres/${id}`,
  labels: `${ADMIN_API_V1_PREFIX}/labels`,
  label: (id: string) => `${ADMIN_API_V1_PREFIX}/labels/${id}`,
  releaseFaq: (releaseId: string) => `${ADMIN_API_V1_PREFIX}/releases/${releaseId}/faq`,
  releaseFaqItem: (releaseId: string, faqId: string) =>
    `${ADMIN_API_V1_PREFIX}/releases/${releaseId}/faq/${faqId}`,
  rounds: `${ADMIN_API_V1_PREFIX}/rounds`,
  wallets: `${ADMIN_API_V1_PREFIX}/wallets`,
  wallet: (id: string) => `${ADMIN_API_V1_PREFIX}/wallets/${id}`,
  walletTransactions: (id: string) => `${ADMIN_API_V1_PREFIX}/wallets/${id}/transactions`,
  userWallet: (userId: string) => `${ADMIN_API_V1_PREFIX}/users/${userId}/wallet`,
  userWalletTransactions: (userId: string) =>
    `${ADMIN_API_V1_PREFIX}/users/${userId}/wallet/transactions`,
  deposits: `${ADMIN_API_V1_PREFIX}/deposits`,
  deposit: (id: string) => `${ADMIN_API_V1_PREFIX}/deposits/${id}`,
  withdrawals: `${ADMIN_API_V1_PREFIX}/withdrawals`,
  withdrawal: (id: string) => `${ADMIN_API_V1_PREFIX}/withdrawals/${id}`,
  holdings: `${ADMIN_API_V1_PREFIX}/holdings`,
  revenueEvents: `${ADMIN_API_V1_PREFIX}/revenue-events`,
  revenueEventsSummary: `${ADMIN_API_V1_PREFIX}/revenue-events/summary`,
  revenueEvent: (id: string) => `${ADMIN_API_V1_PREFIX}/revenue-events/${id}`,
  revenueEventSubmitReview: (id: string) =>
    `${ADMIN_API_V1_PREFIX}/revenue-events/${id}/submit-review`,
  revenueEventApprove: (id: string) => `${ADMIN_API_V1_PREFIX}/revenue-events/${id}/approve`,
  revenueEventCancel: (id: string) => `${ADMIN_API_V1_PREFIX}/revenue-events/${id}/cancel`,
  revenueEventRetry: (id: string) => `${ADMIN_API_V1_PREFIX}/revenue-events/${id}/retry`,
  listings: `${ADMIN_API_V1_PREFIX}/listings`,
  listing: (id: string) => `${ADMIN_API_V1_PREFIX}/listings/${id}`,
  trades: `${ADMIN_API_V1_PREFIX}/trades`,
  trade: (id: string) => `${ADMIN_API_V1_PREFIX}/trades/${id}`,
  secondaryMarketSummary: `${ADMIN_API_V1_PREFIX}/secondary-market/summary`,
  secondaryMarketLiquidity: `${ADMIN_API_V1_PREFIX}/secondary-market/liquidity`,
  secondaryMarketFees: `${ADMIN_API_V1_PREFIX}/secondary-market/fees`,
  distributionsPreview: `${ADMIN_API_V1_PREFIX}/distributions/preview`,
  distributionsPreviewSave: `${ADMIN_API_V1_PREFIX}/distributions/preview/save`,
  distributionsRun: `${ADMIN_API_V1_PREFIX}/distributions/run`,
  platformRevenueSummary: `${ADMIN_API_V1_PREFIX}/platform-revenue/summary`,
  platformRevenueByPeriod: `${ADMIN_API_V1_PREFIX}/platform-revenue/by-period`,
  platformRevenueBySource: `${ADMIN_API_V1_PREFIX}/platform-revenue/by-source`,
  platformRevenueByRelease: `${ADMIN_API_V1_PREFIX}/platform-revenue/by-release`,
  platformRevenueFeeSettingsHistory: `${ADMIN_API_V1_PREFIX}/platform-revenue/fee-settings-history`,
  platformRevenueTransactions: `${ADMIN_API_V1_PREFIX}/platform-revenue/transactions`,
  platformRevenueTransaction: (id: string) => `${ADMIN_API_V1_PREFIX}/platform-revenue/transactions/${id}`,
  platformFees: `${ADMIN_API_V1_PREFIX}/platform-fees`,
  platformRevenue: `${ADMIN_API_V1_PREFIX}/platform-revenue`,
  reports: `${ADMIN_API_V1_PREFIX}/reports`,
  reportsSummary: `${ADMIN_API_V1_PREFIX}/reports/summary`,
  supportTickets: `${ADMIN_API_V1_PREFIX}/support/tickets`,
  supportTicketsSummary: `${ADMIN_API_V1_PREFIX}/support/tickets/summary`,
  supportTicket: (id: string) => `${ADMIN_API_V1_PREFIX}/support/tickets/${id}`,
  disputes: `${ADMIN_API_V1_PREFIX}/disputes`,
  disputesSummary: `${ADMIN_API_V1_PREFIX}/disputes/summary`,
  dispute: (id: string) => `${ADMIN_API_V1_PREFIX}/disputes/${id}`,
  userOperatorContext: (userId: string) => `${ADMIN_API_V1_PREFIX}/users/${userId}/operator-context`,
  financialRules: `${ADMIN_API_V1_PREFIX}/settings/financial-rules`,
  financialRule: (id: string) => `${ADMIN_API_V1_PREFIX}/settings/financial-rules/${id}`,
  financialRuleHistory: (id: string) => `${ADMIN_API_V1_PREFIX}/settings/financial-rules/${id}/history`,
  news: `${ADMIN_API_V1_PREFIX}/news`,
  newsPost: (id: string) => `${ADMIN_API_V1_PREFIX}/news/${id}`,
  newsCover: (id: string) => `${ADMIN_API_V1_PREFIX}/news/${id}/cover`,
  newsPublish: (id: string) => `${ADMIN_API_V1_PREFIX}/news/${id}/publish`,
  newsUnpublish: (id: string) => `${ADMIN_API_V1_PREFIX}/news/${id}/unpublish`,
  newsArchive: (id: string) => `${ADMIN_API_V1_PREFIX}/news/${id}/archive`,
  helpCategories: `${ADMIN_API_V1_PREFIX}/help/categories`,
  helpCategoriesReorder: `${ADMIN_API_V1_PREFIX}/help/categories/reorder`,
  helpCategory: (id: string) => `${ADMIN_API_V1_PREFIX}/help/categories/${id}`,
  helpArticles: `${ADMIN_API_V1_PREFIX}/help/articles`,
  helpArticlesReorder: `${ADMIN_API_V1_PREFIX}/help/articles/reorder`,
  helpArticle: (id: string) => `${ADMIN_API_V1_PREFIX}/help/articles/${id}`,
  helpArticlePublish: (id: string) => `${ADMIN_API_V1_PREFIX}/help/articles/${id}/publish`,
  helpArticleArchive: (id: string) => `${ADMIN_API_V1_PREFIX}/help/articles/${id}/archive`,
  systemStatusComponents: `${ADMIN_API_V1_PREFIX}/system-status/components`,
  systemStatusComponent: (code: string) => `${ADMIN_API_V1_PREFIX}/system-status/components/${code}`,
  systemStatusIncidents: `${ADMIN_API_V1_PREFIX}/system-status/incidents`,
  systemStatusIncidentResolve: (id: string) => `${ADMIN_API_V1_PREFIX}/system-status/incidents/${id}/resolve`,
  systemStatusIncidentUpdates: (id: string) => `${ADMIN_API_V1_PREFIX}/system-status/incidents/${id}/updates`,
  systemAnnouncements: `${ADMIN_API_V1_PREFIX}/system-announcements`,
  systemAnnouncement: (id: string) => `${ADMIN_API_V1_PREFIX}/system-announcements/${id}`,
  systemAnnouncementPublish: (id: string) => `${ADMIN_API_V1_PREFIX}/system-announcements/${id}/publish`,
  systemAnnouncementArchive: (id: string) => `${ADMIN_API_V1_PREFIX}/system-announcements/${id}/archive`,
  systemAnnouncementPreview: (id: string) => `${ADMIN_API_V1_PREFIX}/system-announcements/${id}/preview`,
  operationsStatus: `${ADMIN_API_V1_PREFIX}/operations/status`,
  alerts: `${ADMIN_API_V1_PREFIX}/alerts`,
  alertAcknowledge: (id: string) => `${ADMIN_API_V1_PREFIX}/alerts/${id}/acknowledge`,
  alertResolve: (id: string) => `${ADMIN_API_V1_PREFIX}/alerts/${id}/resolve`,
  complianceRiskFlags: `${ADMIN_API_V1_PREFIX}/compliance/risk-flags`,
  complianceSummary: `${ADMIN_API_V1_PREFIX}/compliance/summary`,
  complianceRiskRules: `${ADMIN_API_V1_PREFIX}/compliance/risk-rules`,
  complianceHistory: `${ADMIN_API_V1_PREFIX}/compliance/history`,
  complianceRiskFlag: (id: string) => `${ADMIN_API_V1_PREFIX}/compliance/risk-flags/${id}`,
  role: (code: string) => `${ADMIN_API_V1_PREFIX}/roles/${code}`,
  roleUsers: (code: string) => `${ADMIN_API_V1_PREFIX}/roles/${code}/users`,
  roles: `${ADMIN_API_V1_PREFIX}/roles`,
  compliance: `${ADMIN_API_V1_PREFIX}/compliance`,
  kycReviews: `${ADMIN_API_V1_PREFIX}/kyc/reviews`,
  kycReviewApprove: (id: string) => `${ADMIN_API_V1_PREFIX}/kyc/reviews/${id}/approve`,
  kycReviewReject: (id: string) => `${ADMIN_API_V1_PREFIX}/kyc/reviews/${id}/reject`,
  legalPolicies: `${ADMIN_API_V1_PREFIX}/legal/policies`,
  treasury: `${ADMIN_API_V1_PREFIX}/treasury`,
  legalPolicy: (id: string) => `${ADMIN_API_V1_PREFIX}/legal/policies/${id}`,
  legalPolicyPublish: (id: string) => `${ADMIN_API_V1_PREFIX}/legal/policies/${id}/publish`,
  legalPolicyArchive: (id: string) => `${ADMIN_API_V1_PREFIX}/legal/policies/${id}/archive`,
  legalCountryRestrictions: `${ADMIN_API_V1_PREFIX}/legal/country-restrictions`,
  settings: `${ADMIN_API_V1_PREFIX}/settings`,
  auditLogs: `${ADMIN_API_V1_PREFIX}/audit-logs`,
  /** @deprecated use auditLogs */
  auditLog: `${ADMIN_API_V1_PREFIX}/audit-logs`,
  referralsSummary: `${ADMIN_API_V1_PREFIX}/referrals/summary`,
  referralsRewards: `${ADMIN_API_V1_PREFIX}/referrals/rewards`,
  referralsPartners: `${ADMIN_API_V1_PREFIX}/referrals/partners`,
  referralRewardApprove: (id: string) => `${ADMIN_API_V1_PREFIX}/referrals/rewards/${id}/approve`,
  referralRewardReject: (id: string) => `${ADMIN_API_V1_PREFIX}/referrals/rewards/${id}/reject`,
  referralPartnerApprove: (id: string) => `${ADMIN_API_V1_PREFIX}/referrals/partners/${id}/approve`,
  referralPartnerReject: (id: string) => `${ADMIN_API_V1_PREFIX}/referrals/partners/${id}/reject`,
  referralPartnerSuspend: (id: string) => `${ADMIN_API_V1_PREFIX}/referrals/partners/${id}/suspend`,
  analyticsOverview: `${ADMIN_API_V1_PREFIX}/analytics/overview`,
  analyticsFinanceSummary: `${ADMIN_API_V1_PREFIX}/analytics/finance/summary`,
  analyticsFinanceCashflow: `${ADMIN_API_V1_PREFIX}/analytics/finance/cashflow`,
  analyticsFinanceFees: `${ADMIN_API_V1_PREFIX}/analytics/finance/fees`,
  analyticsFinanceWithdrawalProcessing: `${ADMIN_API_V1_PREFIX}/analytics/finance/withdrawal-processing`,
  analyticsFinanceFailures: `${ADMIN_API_V1_PREFIX}/analytics/finance/failures`,
  analyticsUsersSummary: `${ADMIN_API_V1_PREFIX}/analytics/users/summary`,
  analyticsUsersGrowth: `${ADMIN_API_V1_PREFIX}/analytics/users/growth`,
  analyticsUsersFunnel: `${ADMIN_API_V1_PREFIX}/analytics/users/funnel`,
  analyticsUsersSegments: `${ADMIN_API_V1_PREFIX}/analytics/users/segments`,
  analyticsUsersTopHolders: `${ADMIN_API_V1_PREFIX}/analytics/users/top-holders`,
  analyticsUsersFinancialSegments: `${ADMIN_API_V1_PREFIX}/analytics/users/financial-segments`,
  analyticsUsersDormant: `${ADMIN_API_V1_PREFIX}/analytics/users/dormant`,
  analyticsUsersRiskUsers: `${ADMIN_API_V1_PREFIX}/analytics/users/risk-users`,
  analyticsTracksSummary: `${ADMIN_API_V1_PREFIX}/analytics/tracks/summary`,
  analyticsTracksRoundProgress: `${ADMIN_API_V1_PREFIX}/analytics/tracks/round-progress`,
  analyticsTracksRevenue: `${ADMIN_API_V1_PREFIX}/analytics/tracks/revenue`,
  analyticsTracksHolders: `${ADMIN_API_V1_PREFIX}/analytics/tracks/holders`,
  analyticsTracksSecondaryActivity: `${ADMIN_API_V1_PREFIX}/analytics/tracks/secondary-activity`,
  analyticsTracksUnits: `${ADMIN_API_V1_PREFIX}/analytics/tracks/units`,
  analyticsTracksReadiness: `${ADMIN_API_V1_PREFIX}/analytics/tracks/readiness`,
  analyticsTracksTop: `${ADMIN_API_V1_PREFIX}/analytics/tracks/top`,
  analyticsMarketSummary: `${ADMIN_API_V1_PREFIX}/analytics/market/summary`,
  analyticsMarketVolume: `${ADMIN_API_V1_PREFIX}/analytics/market/volume`,
  analyticsMarketListings: `${ADMIN_API_V1_PREFIX}/analytics/market/listings`,
  analyticsMarketTrades: `${ADMIN_API_V1_PREFIX}/analytics/market/trades`,
  analyticsMarketTopUsers: `${ADMIN_API_V1_PREFIX}/analytics/market/top-users`,
  analyticsMarketFees: `${ADMIN_API_V1_PREFIX}/analytics/market/fees`,
  analyticsMarketDepth: `${ADMIN_API_V1_PREFIX}/analytics/market/depth`,
  analyticsMarketLiquidity: `${ADMIN_API_V1_PREFIX}/analytics/market/liquidity`,
  analyticsMarketPrices: `${ADMIN_API_V1_PREFIX}/analytics/market/prices`,
  analyticsMarketRisk: `${ADMIN_API_V1_PREFIX}/analytics/market/risk`,
  analyticsRevenueSummary: `${ADMIN_API_V1_PREFIX}/analytics/revenue/summary`,
  analyticsRevenueEvents: `${ADMIN_API_V1_PREFIX}/analytics/revenue/events`,
  analyticsRevenueDistributions: `${ADMIN_API_V1_PREFIX}/analytics/revenue/distributions`,
  analyticsRevenueByTrack: `${ADMIN_API_V1_PREFIX}/analytics/revenue/by-track`,
  analyticsRevenuePayouts: `${ADMIN_API_V1_PREFIX}/analytics/revenue/payouts`,
  analyticsRevenuePipeline: `${ADMIN_API_V1_PREFIX}/analytics/revenue/pipeline`,
  analyticsRevenueSplit: `${ADMIN_API_V1_PREFIX}/analytics/revenue/split`,
  analyticsRevenueTopHolders: `${ADMIN_API_V1_PREFIX}/analytics/revenue/top-holders`,
  analyticsRevenueFailed: `${ADMIN_API_V1_PREFIX}/analytics/revenue/failed`,
  analyticsRevenueReconciliation: `${ADMIN_API_V1_PREFIX}/analytics/revenue/reconciliation`,
  analyticsRiskSummary: `${ADMIN_API_V1_PREFIX}/analytics/risk/summary`,
  analyticsRiskBySeverity: `${ADMIN_API_V1_PREFIX}/analytics/risk/by-severity`,
  analyticsRiskByType: `${ADMIN_API_V1_PREFIX}/analytics/risk/by-type`,
  analyticsRiskQueueAging: `${ADMIN_API_V1_PREFIX}/analytics/risk/queue-aging`,
  analyticsRiskHighValueOperations: `${ADMIN_API_V1_PREFIX}/analytics/risk/high-value-operations`,
  analyticsRiskQueue: `${ADMIN_API_V1_PREFIX}/analytics/risk/queue`,
  analyticsRiskRulesPerformance: `${ADMIN_API_V1_PREFIX}/analytics/risk/rules-performance`,
  analyticsRiskRepeatOffenders: `${ADMIN_API_V1_PREFIX}/analytics/risk/repeat-offenders`,
  analyticsRiskFreezeImpact: `${ADMIN_API_V1_PREFIX}/analytics/risk/freeze-impact`,
  analyticsRiskResolutionQuality: `${ADMIN_API_V1_PREFIX}/analytics/risk/resolution-quality`,
  analyticsSupportSummary: `${ADMIN_API_V1_PREFIX}/analytics/support/summary`,
  analyticsSupportByStatus: `${ADMIN_API_V1_PREFIX}/analytics/support/by-status`,
  analyticsSupportByCategory: `${ADMIN_API_V1_PREFIX}/analytics/support/by-category`,
  analyticsSupportResponseTime: `${ADMIN_API_V1_PREFIX}/analytics/support/response-time`,
  analyticsSupportByManager: `${ADMIN_API_V1_PREFIX}/analytics/support/by-manager`,
  analyticsSupportQueue: `${ADMIN_API_V1_PREFIX}/analytics/support/queue`,
  analyticsSupportSla: `${ADMIN_API_V1_PREFIX}/analytics/support/sla`,
  analyticsSupportFinanceRelated: `${ADMIN_API_V1_PREFIX}/analytics/support/finance-related`,
  analyticsSupportEscalations: `${ADMIN_API_V1_PREFIX}/analytics/support/escalations`,
  analyticsSupportWorkload: `${ADMIN_API_V1_PREFIX}/analytics/support/workload`,
  analyticsSupportResolutionQuality: `${ADMIN_API_V1_PREFIX}/analytics/support/resolution-quality`,
  analyticsSupportProductPainPoints: `${ADMIN_API_V1_PREFIX}/analytics/support/product-pain-points`,
} as const;

export { getAdminApiBaseUrl };

/** `mock` for local UI demos only; `live` calls AdminApiClient (default). */
export type AdminDataSource = DataSourceMode;

export function getAdminDataSource(): AdminDataSource {
  return getAdminDataSourceFromEnv();
}
